name: Deploy Vue App to GitHub Pages

on:
  push:
    branches: [ main ]  # Set this to your default branch name (main or master)
  workflow_dispatch:    # Allows manual triggering of the workflow

# Set permissions for GitHub token
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use an appropriate Node.js version for your project
          
      - name: Install dependencies
        run: npm ci  # Use 'npm ci' for clean install
        
      - name: Build Vue app
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # The folder the action will deploy, default for Vue
          branch: gh-pages  # The branch the action should deploy to
          clean: true  # Automatically remove deleted files from the deploy branch
          force: true  # Force the deployment
          attempt-limit: 3  # Try up to 3 times if deployment fails
