name: Deploy Vue App to GitHub Pages

on:
  push:
    branches: [ main ]  # Set this to your default branch name (main or master)
  workflow_dispatch:    # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use an appropriate Node.js version for your project
          
      - name: Install dependencies
        run: npm ci  # Use 'npm ci' for clean install
      
      - name: Install some more
        run: npm install vue-router

      - name: Install one more
        run: npm install axios
        
      - name: Build Vue app
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # The folder the action will deploy, default for Vue
          branch: gh-pages  # The branch the action should deploy to
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
